import type { LucideIcon } from 'lucide-react';
import { BarChart3, CalendarDays, ClipboardCheck, CreditCard, FileClock, Package, Plus, Settings, Ship, UserCog, UsersRound, WalletCards } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

type Metric = [string, string, LucideIcon];

const emptyRows: string[][] = [];

export function AdminDashboardPage() { return <PageShell label="Dashboard" title="Operations overview" text="Live booking, payment, vehicle, staff, and revenue data will appear here after Supabase connection." action="Refresh" metrics={[["New Bookings", "0", CalendarDays], ["Today Rides", "0", ClipboardCheck], ["Pending Payments", "AED 0.00", WalletCards], ["Available Vehicles", "0", Ship]]}><Empty title="No live data connected yet" text="Dummy dashboard numbers have been removed." /></PageShell>; }
export function AdminStaffPage() { return <PageShell label="Staff / Users" title="Staff and login access" text="Create admins, booking staff, managers, operations staff, and finance users with role-based access." action="Add Staff" metrics={[["Active Staff", "0", UserCog], ["Managers", "0", UsersRound], ["Inactive Staff", "0", FileClock]]}><Records columns={["Staff Name", "Role", "Email / Phone", "Status"]} empty="No staff users added yet." /></PageShell>; }
export function AdminPackagesPage() { return <PageShell label="Packages / Products" title="Website packages and product cards" text="Add Jet Ski, Jet Car, rental, and sales inquiry packages. Active packages will power website cards and booking selection." action="Add Package" metrics={[["Active Packages", "0", Package], ["Rental Packages", "0", CalendarDays], ["Sales Inquiries", "0", FileClock]]}><Records columns={["Package", "Category", "Duration / Type", "Price + VAT", "Status"]} empty="No packages added yet." /></PageShell>; }
export function AdminVehiclesPage() { return <PageShell label="Vehicles / Fleet" title="Vehicle master list" text="Add real Jet Skis and Jet Cars with one main image, capacity, status, and maintenance notes." action="Add Vehicle" metrics={[["Jet Skis", "0", Ship], ["Jet Cars", "0", Ship], ["Maintenance", "0", Settings]]}><Records columns={["Vehicle Code", "Vehicle Name", "Type", "Capacity", "Status"]} empty="No vehicles added yet." /></PageShell>; }
export function AdminBookingsPage() { return <PageShell label="Bookings" title="Booking requests" text="Website bookings will appear here for confirmation, cancellation, rescheduling, and handover to manager operations." action="New Manual Booking" metrics={[["New Requests", "0", CalendarDays], ["Confirmed", "0", ClipboardCheck], ["Cancelled", "0", FileClock]]}><Records columns={["Booking Code", "Customer", "Package", "Date / Time", "Status"]} empty="No booking requests yet." /></PageShell>; }
export function AdminSchedulePage() { return <PageShell label="Schedule" title="Daily and weekly schedule" text="Calendar view for rides, time slots, assigned vehicles, and manager status updates." action="Add Schedule Note" metrics={[["Today", "0", CalendarDays], ["Upcoming", "0", FileClock], ["Assigned", "0", ClipboardCheck]]}><Empty title="Schedule is ready for integration" text="Confirmed bookings will populate this page once booking data is connected." /></PageShell>; }
export function AdminAssignmentsPage() { return <PageShell label="Assignments" title="Vehicle and crew assignment" text="Manager assigns actual vehicles, captain or guide, payment collection, and ride status here." action="Assign Vehicle" metrics={[["Pending Assignment", "0", ClipboardCheck], ["Assigned Today", "0", Ship], ["Completed", "0", CalendarDays]]}><Records columns={["Booking", "Package", "Vehicle", "Crew", "Status"]} empty="No confirmed bookings pending assignment." /></PageShell>; }
export function ManagerOperationsPage() { return <PageShell label="Manager" title="Manager operations dashboard" text="Confirmed rides, vehicle assignment, crew assignment, payment collection, and ride completion workflow." action="Update Status" metrics={[["Confirmed Rides", "0", ClipboardCheck], ["Vehicles Assigned", "0", Ship], ["Payments Pending", "AED 0.00", CreditCard]]}><Empty title="No confirmed rides yet" text="Confirmed bookings will appear here for manager actions." /></PageShell>; }
export function AdminPaymentsPage() { return <PageShell label="Payments" title="Payment tracking" text="Track not paid, partial, paid, refunded, payment method, amount paid, balance, and collection notes." action="Record Payment" metrics={[["Collected", "AED 0.00", WalletCards], ["Pending", "AED 0.00", FileClock], ["Refunds", "AED 0.00", CreditCard]]}><Records columns={["Booking", "Customer", "Total", "Paid", "Balance", "Status"]} empty="No payment records yet." /></PageShell>; }
export function AdminCustomersPage() { return <PageShell label="Customers" title="Customer directory" text="Customer records, contact details, booking history, repeat customer status, and admin notes." action="Add Customer" metrics={[["Customers", "0", UsersRound], ["Repeat Customers", "0", UsersRound], ["Priority", "0", UsersRound]]}><Records columns={["Customer", "Phone", "Email", "Bookings", "Status"]} empty="No customer records yet." /></PageShell>; }
export function AdminMaintenancePage() { return <PageShell label="Maintenance" title="Vehicle maintenance" text="Track vehicle issues, maintenance dates, costs, status, and available-again dates." action="Add Maintenance" metrics={[["Open Issues", "0", Settings], ["In Service", "0", Ship], ["Closed", "0", ClipboardCheck]]}><Records columns={["Vehicle", "Issue", "Date", "Cost", "Status"]} empty="No maintenance records yet." /></PageShell>; }
export function AdminReportsPage() { return <PageShell label="Reports" title="Business reports" text="Daily revenue, monthly revenue, bookings by package, bookings by vehicle, payment reports, cancellations, and staff performance." action="Export" metrics={[["Revenue", "AED 0.00", BarChart3], ["Bookings", "0", CalendarDays], ["Vehicle Usage", "0%", Ship]]}><Empty title="Reports will use live database records" text="Dummy charts have been removed." /></PageShell>; }
export function AdminSettingsPage() { return <PageShell label="Settings" title="Company and booking settings" text="Manage company details, WhatsApp, email, VAT percentage, meeting point, booking terms, and cancellation policy." action="Save Settings" metrics={[["VAT", "5%", Settings], ["Booking Flow", "Ready", ClipboardCheck], ["Location", "Set", Ship]]}><Records columns={["Setting", "Current Value", "Status"]} empty="Settings fields are ready for Supabase connection." /></PageShell>; }
export function AdminInventoryPage() { return <AdminPackagesPage />; }
export function AdminCouponsPage() { return <AdminPackagesPage />; }
export function AdminReviewsPage() { return <AdminCustomersPage />; }

function PageShell({ label, title, text, action, metrics, children }: { label: string; title: string; text: string; action: string; metrics: Metric[]; children: React.ReactNode }) { return <div className="flex flex-col gap-5"><div className="flex flex-col gap-4 rounded-[1.75rem] border border-white/80 bg-white/85 p-5 shadow-[0_18px_45px_rgba(8,37,50,0.06)] lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><div className="mb-3 flex flex-wrap items-center gap-2"><span className="rounded-full bg-primary-50 px-3 py-1 text-xs font-bold uppercase tracking-[0.16em] text-primary">{label}</span><Badge variant="secondary" className="rounded-full">Database ready</Badge></div><h1 className="font-heading text-3xl font-semibold text-foreground">{title}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div><Button type="button"><Plus data-icon aria-hidden="true" />{action}</Button></div><div className="grid gap-4 md:grid-cols-3 xl:grid-cols-4">{metrics.map(([metric, value, Icon]) => <Card key={metric}><CardContent className="flex items-center justify-between gap-4 p-5"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">{metric}</p><p className="mt-2 font-heading text-2xl font-semibold text-foreground">{value}</p></div><span className="flex size-11 items-center justify-center rounded-2xl bg-primary-50 text-primary"><Icon className="size-5" aria-hidden="true" /></span></CardContent></Card>)}</div>{children}</div>; }
function Empty({ title, text }: { title: string; text: string }) { return <Card><CardContent className="p-8 text-center"><p className="font-heading text-xl font-semibold text-foreground">{title}</p><p className="mx-auto mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{text}</p></CardContent></Card>; }
function Records({ columns, empty }: { columns: string[]; empty: string }) { return <Card><CardHeader><CardTitle className="text-base">Records</CardTitle><CardDescription>Live records will show here after database connection.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow>{columns.map((column) => <TableHead key={column}>{column}</TableHead>)}</TableRow></TableHeader><TableBody>{emptyRows.length ? null : <TableRow><TableCell colSpan={columns.length} className="h-28 text-center text-sm text-muted-foreground">{empty}</TableCell></TableRow>}</TableBody></Table></CardContent></Card>; }
