'use client';

import { CircleDollarSign, Landmark, ShieldCheck, WalletCards } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { formatAed } from './operations-data';
import { useOperations } from './operations-store';
import { CollectionBadge, PageHeader, PaymentBadge, SummaryTile } from './shared';

export function AdminPaymentsPage() {
  const { bookings } = useOperations();
  const received = bookings.reduce((sum, booking) => sum + booking.amountReceived, 0);
  const pending = bookings.reduce((sum, booking) => sum + booking.amountPending, 0);
  const heldBy = (statuses: string[]) => bookings.filter((booking) => statuses.includes(booking.collectionStatus)).reduce((sum, booking) => sum + booking.amountReceived, 0);
  return <div className="flex flex-col gap-6"><PageHeader title="Payments & collections" description="Track every received amount, outstanding balance, payment method, and current cash custodian." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><SummaryTile label="Total Received" value={formatAed(received)} detail="All payment methods" icon={CircleDollarSign} /><SummaryTile label="Total Pending" value={formatAed(pending)} detail="Outstanding balance" icon={WalletCards} tone="gold" /><SummaryTile label="With Manager" value={formatAed(heldBy(['With Manager']))} detail="Pending handover" icon={WalletCards} tone="gold" /><SummaryTile label="Captain / Driver" value={formatAed(heldBy(['With Captain', 'With Driver']))} detail="Pending handover" icon={WalletCards} tone="gold" /><SummaryTile label="Deposited / Verified" value={formatAed(heldBy(['Deposited', 'Verified by Finance']))} detail="Finance controlled" icon={ShieldCheck} /></div><Card><CardHeader><CardTitle>Payment ledger</CardTitle><CardDescription>Operational payment and collection state by booking.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Booking</TableHead><TableHead>Customer</TableHead><TableHead>Final</TableHead><TableHead>Received</TableHead><TableHead>Pending</TableHead><TableHead>Method</TableHead><TableHead>Status</TableHead><TableHead>Collected by</TableHead><TableHead>Collection</TableHead></TableRow></TableHeader><TableBody>{bookings.map((booking) => <TableRow key={booking.id}><TableCell className="font-semibold text-foreground">{booking.bookingCode}</TableCell><TableCell>{booking.customerName}</TableCell><TableCell>{formatAed(booking.finalAmount)}</TableCell><TableCell className="font-medium text-foreground">{formatAed(booking.amountReceived)}</TableCell><TableCell className="font-medium text-gold-deep">{formatAed(booking.amountPending)}</TableCell><TableCell>{booking.paymentMethod}</TableCell><TableCell><PaymentBadge status={booking.paymentStatus} /></TableCell><TableCell>{booking.paymentCollectedBy || '—'}</TableCell><TableCell><CollectionBadge status={booking.collectionStatus} /></TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-4"><Landmark className="size-5 text-primary" aria-hidden="true" /><p className="text-sm text-muted-foreground">Finance completes custody by changing deposited funds to <span className="font-semibold text-foreground">Verified by Finance</span>.</p></CardContent></Card></div>;
}
