'use client';

import { recordAuditLog } from '@/lib/audit-log';

export type ExportColumn<T> = {
  heading: string;
  value: (row: T) => string | number | null | undefined;
};

type ExportContext<T> = {
  reportType: string;
  dateFrom: string;
  dateTo: string;
  filters: Record<string, unknown>;
  rows: T[];
  columns: ExportColumn<T>[];
  generatedBy: string;
  summary?: Array<{ label: string; value: string }>;
};

function slug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function filename(context: ExportContext<unknown>, extension: string) {
  return `edrive-${slug(context.reportType)}-${context.dateFrom || 'all'}-to-${context.dateTo || 'all'}.${extension}`;
}

function csvCell(value: unknown) {
  const text = String(value ?? '').replace(/\r?\n/g, ' ');
  return `"${text.replace(/"/g, '""')}"`;
}

async function auditExport<T>(context: ExportContext<T>, format: 'csv' | 'pdf') {
  const appliedFilterNames = Object.entries(context.filters)
    .filter(([, value]) => value !== '' && value !== false && value != null)
    .map(([key]) => key);
  const result = await recordAuditLog({
    module: 'finance',
    action: 'finance_report_exported',
    summary: `${context.reportType} exported as ${format.toUpperCase()}.`,
    entityType: 'finance_report',
    entityLabel: context.reportType,
    metadata: {
      format,
      report_type: context.reportType,
      date_from: context.dateFrom,
      date_to: context.dateTo,
      applied_filter_names: appliedFilterNames,
      row_count: context.rows.length
    }
  });
  return result.ok ? '' : 'The report was downloaded, but its audit entry could not be saved.';
}

export async function exportFinanceCsv<T>(context: ExportContext<T>) {
  const lines = [
    context.columns.map((column) => csvCell(column.heading)).join(','),
    ...context.rows.map((row) => context.columns.map((column) => csvCell(column.value(row))).join(','))
  ];
  const blob = new Blob([`\uFEFF${lines.join('\r\n')}`], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename(context as ExportContext<unknown>, 'csv');
  anchor.click();
  URL.revokeObjectURL(url);
  return auditExport(context, 'csv');
}

export async function exportFinancePdf<T>(context: ExportContext<T>) {
  const [{ jsPDF }, autoTableModule] = await Promise.all([import('jspdf'), import('jspdf-autotable')]);
  const document = new jsPDF({ orientation: context.columns.length > 6 ? 'landscape' : 'portrait', unit: 'pt', format: 'a4' });
  document.setTextColor(8, 71, 82);
  document.setFontSize(18);
  document.text('eDrive Water Sports', 36, 36);
  document.setFontSize(13);
  document.text(context.reportType, 36, 58);
  document.setTextColor(80);
  document.setFontSize(9);
  document.text(`Period: ${context.dateFrom || 'All'} to ${context.dateTo || 'All'} | Generated: ${new Intl.DateTimeFormat('en-AE', { timeZone: 'Asia/Dubai', dateStyle: 'medium', timeStyle: 'short' }).format(new Date())}`, 36, 76);
  document.text(`Generated by: ${context.generatedBy || 'Finance user'}`, 36, 90);
  let startY = 104;
  if (context.summary?.length) {
    document.text(context.summary.map((item) => `${item.label}: ${item.value}`).join(' | '), 36, startY);
    startY += 14;
  }
  autoTableModule.default(document, {
    startY,
    head: [context.columns.map((column) => column.heading)],
    body: context.rows.map((row) => context.columns.map((column) => String(column.value(row) ?? '-'))),
    styles: { fontSize: 7, cellPadding: 3, overflow: 'linebreak' },
    headStyles: { fillColor: [8, 91, 103] },
    didDrawPage: ({ pageNumber }) => {
      document.setFontSize(8);
      document.text(`Page ${pageNumber}`, document.internal.pageSize.getWidth() - 60, document.internal.pageSize.getHeight() - 18);
    }
  });
  document.save(filename(context as ExportContext<unknown>, 'pdf'));
  return auditExport(context, 'pdf');
}

