import { companyInfo } from '@/lib/company-info';
import type { PublicMessages } from '@/lib/i18n/types';

export const enMessages: PublicMessages = {
  shared: {
    home: 'Home', rentals: 'Rentals', fleet: 'Fleet', membership: 'Membership', contact: 'Contact', myBooking: 'My Booking', staffLogin: 'Staff Login', toggleNavigation: 'Toggle navigation', language: 'Language', selectLanguage: 'Select website language',
    footerIntro: `Private jet ski and jet car experiences from ${companyInfo.locationName}, prepared with a premium fleet and attentive local support.`, explore: 'Explore', allRentals: 'All Rentals', jetSkiRentals: 'Jet Ski Rentals', jetCarRentals: 'Jet Car Rentals', bookRide: 'Book Ride', trackMyBooking: 'Track My Booking', privacyPolicy: 'Privacy Policy', terms: 'Terms & Conditions', refundPolicy: 'Refund / Replacement Policy', rights: '© 2026 eDrive Water Sports. All rights reserved.', bookYourRide: 'Book your ride', whatsappLabel: 'WhatsApp', whatsappAria: 'Contact eDrive on WhatsApp', homeAria: 'eDrive Water Sports home'
  },
  home: {
    heroEyebrow: 'eDrive Water Sports', heroTitleLine1: 'Jet Ski & Jet Car', heroTitleLine2: 'Dubai Islands', heroText: 'Book premium jet ski rentals, luxury jet car rides, and Dubai water sports experiences with clear pricing and fast support.', checkAvailability: 'Check Availability', carouselAria: 'eDrive Water Sports homepage highlights', viewPackages: 'View Ride Packages', whatsappTeam: 'WhatsApp Team',
    summerEyebrow: 'Limited-Time Summer Offers', summerTitle: 'Make a Splash This Summer', summerTagline: 'Ride More. Save More.', summerText: 'Unlock special summer prices on selected Jet Ski and Jet Car experiences at Dubai Islands. Choose your ride, reserve your preferred time and make this summer unforgettable.', summerOffer: 'Offer', summerOffers: 'Offers', summerLive: 'Live', from: 'From', exploreSummer: 'Explore Summer Offers', bookSummer: 'Book Your Summer Ride', previousSlide: 'Previous hero slide', nextSlide: 'Next hero slide', slideOneAria: '1 of 2: eDrive Water Sports', slideTwoAria: '2 of 2: Summer Offers', heroFallbackAlt: 'Jet ski and jet car riding across the Dubai waterfront',
    experiencesTitle: 'Choose Your Water Experience', experiencesText: 'Start with a Jet Ski or Jet Car experience, then compare the available ride durations and prices.', jetSkiTitle: 'Book Jet Ski Ride', jetSkiText: 'Choose a premium Jet Ski experience, then compare available ride durations and seating options.', jetSkiCta: 'View Jet Ski Packages', jetCarTitle: 'Book Jet Car Ride', jetCarText: 'Discover a luxury Jet Car experience for couples, families, celebrations, and memorable Dubai moments.', jetCarCta: 'View Jet Car Packages',
    membershipEyebrow: 'eDrive Membership', membershipTitle: 'Make Every Ride More Rewarding', membershipText: 'Discover priority benefits, exclusive offers, and dedicated support designed for returning eDrive guests.', membershipCta: 'Explore Membership', membershipImageAlt: 'eDrive Membership card',
    whyTitle: 'Why Choose eDrive', whyText: 'A premium Dubai water sports experience built around clear packages, safety support, smooth booking, and guest-focused service.', whyItems: [
      { title: 'Dubai Islands Location', text: `Start your ride from ${companyInfo.locationName} with clear arrival guidance and team support.` },
      { title: 'Safety First', text: 'Every experience includes a safety briefing, life jacket support, and guidance from the eDrive team.' },
      { title: 'Fast WhatsApp Support', text: 'Get quick help with availability, timing, ride options, and special requests before you arrive.' },
      { title: 'Easy Booking', text: 'Choose your ride, duration, date, time, and guest count, then submit your request in minutes.' }
    ],
    howEyebrow: 'How it works', howTitle: 'From package choice to confirmed water time', howText: 'Choose your ride, share your preferred timing, and our team will confirm availability before you arrive.', howItems: [
      { title: 'Choose your ride', text: 'Select a jet ski, jet car, or package that matches your group and preferred timing.' },
      { title: 'Pick date and time', text: 'Share your preferred slot, guest count, and any celebration or group details.' },
      { title: 'Team confirms', text: 'Our team checks availability and confirms the final details before your water sports experience.' }
    ],
    helpEyebrow: 'Need help choosing?', helpTitle: 'Talk to eDrive before you book.', helpText: 'Tell us your date, number of guests, preferred ride, or whether you need help with an eDrive Signature Membership inquiry.', chatWhatsapp: 'Chat on WhatsApp', callNow: 'Call Now'
  },
  packages: {
    defaultTitle: 'Ride Packages', loading: 'Loading packages', count: 'packages', unavailable: 'Ride packages could not be loaded right now. Please retry or contact the eDrive team for the latest availability.', empty: 'No online packages are available at this moment. Contact the eDrive team to confirm the latest ride options and timings.', duration: 'Duration', capacity: 'Capacity', upToGuests: 'Up to {count} guests', perRide: 'per ride', bookPackage: 'Book This Package', viewPackage: 'View Package', package: 'Package', jetSki: 'Jet Ski', jetCar: 'Jet Car', yacht: 'Yacht', activeOffer: 'Active offer', regularPrice: 'Regular price', offerPrice: 'Offer price', savings: 'Savings', save: 'Save', price: 'price'
  },
  fleet: {
    exploreFleet: 'Explore Fleet', bookRide: 'Book a Ride', qualityTitle: 'Fleet Quality & Ride Support', qualityText: 'Every public fleet unit is supported by clear arrival guidance, safety preparation, and booking confirmation before your experience.', qualityItems: [
      { title: 'Dubai Islands Location', text: `Start your ride from ${companyInfo.locationName} with clear arrival guidance and team support.` },
      { title: 'Safety First', text: 'Every experience includes a safety briefing, life jacket support, and guidance from the eDrive team.' },
      { title: 'Fast WhatsApp Support', text: 'Get quick help with availability, timing, ride options, and special requests before you arrive.' },
      { title: 'Easy Booking', text: 'Choose your ride, duration, date, time, and guest count, then submit your request in minutes.' }
    ], ctaEyebrow: 'Choose your ride package', ctaTitle: 'Compare current durations and prices.', ctaText: 'Open the rentals catalog to choose a Jet Ski or Jet Car package that matches your group and preferred ride time.', allPackages: 'View All Packages',
    filtersAria: 'Filter fleet vehicles', all: 'All Fleet', jetSkis: 'Jet Skis', jetCars: 'Jet Cars', loading: 'Loading fleet...', unavailable: 'Fleet details could not be loaded right now. Please retry or contact the eDrive team.', empty: 'No fleet vehicles match this filter.', available: 'Available', assigned: 'Assigned', inUse: 'In Use', reserved: 'Reserved', jetSki: 'Jet Ski', jetCar: 'Jet Car', registration: 'Registration', capacity: 'Capacity', guests: 'guests', viewPackages: 'View Packages'
  },
  booking: {
    steps: ['Select Package', 'Select Duration', 'Vehicles & Guests', 'Date & Time', 'Contact Details', 'Review & Submit'], preparing: 'Preparing Booking', preparingText: 'Preparing your ride options...', summary: 'View booking summary', stepOf: 'Step {current} of {total}', back: 'Back', continue: 'Continue', reviewBooking: 'Review Booking', submit: 'Submit Booking Request', packageLoadError: 'Ride packages could not be loaded. Please retry the page or contact the eDrive team on WhatsApp.', choosePackage: 'Choose your ride package', choosePackageText: 'Select the experience that matches your group.', noPackages: 'No packages are currently available.', select: 'Select', selected: 'Selected', chooseDuration: 'Choose your preferred duration', vehicles: 'Vehicles', guests: 'Guests', vehicle: 'vehicle', guest: 'guest', capacityNote: 'Capacity: up to {count} guests', capacityExceeded: 'Guest count exceeds the selected vehicle capacity.', preferredDate: 'Preferred date', preferredTime: 'Preferred time', datePlaceholder: 'Select your ride date', timePlaceholder: 'Select a time', scheduleNote: 'Times are shown in Dubai time. Future available slots only.', fullName: 'Full name', phone: 'Phone / WhatsApp', email: 'Email', optional: 'optional', hotelArea: 'Hotel or area', notes: 'Notes', namePlaceholder: 'Your full name', phonePlaceholder: '+971 50 000 0000', emailPlaceholder: 'you@example.com', hotelPlaceholder: 'Hotel, residence, or area', notesPlaceholder: 'Share any celebration, accessibility, or group details.', reviewTitle: 'Review your booking request', contact: 'Contact', service: 'Service', date: 'Date', time: 'Time', duration: 'Duration', party: 'Party', package: 'Package', meetingPoint: 'Meeting point', notSelected: 'Not selected', requestQuote: 'Request quote', liveSummary: 'Live Summary', selectedExperience: 'Selected experience', seater: 'seater', noPaymentNow: 'No payment now. Final details are confirmed by our team.', selectedVehicle: 'Selected vehicle', costBreakdown: 'Cost Breakdown', regularUnitPrice: 'Regular unit price', offerUnitPrice: 'Offer unit price', vehicleQuantity: 'Vehicle quantity', subtotal: 'Sub Total', vat: 'VAT (5%)', pricing: 'Pricing', totalPrice: 'Total price', includesVat: 'Includes 5% VAT', websiteRequest: 'Website request', pending: 'Pending',
    info: [
      { title: "What's Included", text: 'Safety briefing, life jacket, dock assistance, route guidance, and marina team support.' },
      { title: 'What to Bring', text: 'A valid photo ID, comfortable swimwear, sun protection, extra clothes, and a towel.' },
      { title: 'Meeting Point', text: `${companyInfo.locationName}, ${companyInfo.locationAddress}. Please arrive 20 minutes before your confirmed time.` },
      { title: 'Important Information', text: 'Riders must follow the crew briefing. A valid ID is required and age restrictions may apply to drivers.' },
      { title: 'Cancellation / Weather Policy', text: 'Marine conditions are monitored daily. If conditions are unsafe, our team will help reschedule your experience.' }
    ],
    submittingTitle: 'Submitting Booking Request', receivedTitle: 'Booking Request Received', failedTitle: 'Booking Request Not Sent', pendingConfirmation: 'Pending Confirmation', secureSubmission: 'Secure Submission', actionRequired: 'Action Required', savedThankYou: 'Thank you, {name}. Our booking team will check availability and contact you shortly.', savingText: 'Please wait while we securely save your booking request.', failedText: 'Your request has not been recorded yet. Retry below or send the details to our team on WhatsApp.', sending: 'Sending your request...', requestReceived: 'Request received successfully', automaticFailure: 'We could not save the request automatically.', retryHelp: 'Please retry or WhatsApp the team.', retry: 'Retry Submission', submitting: 'Submitting', notSubmitted: 'Not Submitted', inquiry: 'Inquiry', reference: 'Reference', generatedAfter: 'Generated after submission', estimatedTotal: 'Estimated Total', paymentAfterConfirmation: 'No payment was taken. Payment details are shared after confirmation.', teamContact: 'Our team will contact you shortly to confirm your booking details.', unconfirmedSummary: 'This summary is not a confirmed booking until the request is successfully saved.', openMaps: 'Open in Google Maps', whatNext: 'What happens next', whatNextText: 'Our team reviews your preferred date, time, and fleet availability.', payment: 'Payment', needAdd: 'Need to add something?', needAddText: 'Send the booking team your reference on WhatsApp or check your booking status after submission.', checkStatus: 'Check Status', whatsappUs: 'WhatsApp us', backHome: 'Back to Home', bookAnother: 'Book Another Experience', minutes: 'minutes', hours: 'hours'
  },
  tracker: {
    eyebrow: 'My Booking', title: 'Track your booking', intro: 'Enter your booking code and the same phone number or email used when submitting your request.', code: 'Booking Code', codePlaceholder: 'Example: ED-8D91AE26C331', contact: 'Phone or Email', contactPlaceholder: 'Same contact used for booking', checking: 'Checking booking...', submit: 'Check Booking Status', rateLimit: 'Please wait a few seconds before trying again.', notFound: 'Booking not found. Check the booking code and use the same phone number or email entered during booking.', unavailable: 'Booking status is temporarily unavailable. Please try again or contact our support team.', greeting: 'Hello {name}, here is your latest booking status.', journey: 'Booking journey', pending: 'Pending', confirmed: 'Confirmed', inProgress: 'In Progress', completed: 'Completed', noShow: 'No Show', cancelled: 'Cancelled', date: 'Date', timeTbc: 'Time to be confirmed', experience: 'Experience', waterExperience: 'Water sports experience', meetingPoint: 'Meeting Point', finalInstructions: 'Final instructions are shared by our team.', assignedVehicle: 'Assigned Vehicle', toBeAssigned: 'To be assigned', vehicleNote: 'Vehicle may be assigned shortly before the ride.', payment: 'Payment', paid: 'Paid', balance: 'Balance', bookingTotal: 'Booking Total', created: 'Created', needHelp: 'Need help with this booking?', helpText: 'Our team can help with timing, directions and booking updates.', contactSupport: 'Contact Support', tbc: 'To be confirmed'
  },
  contactForm: {
    formTitle: 'Send an inquiry', formText: 'Share your preferred ride, date, group size, or question and our team will respond.', name: 'Name', phone: 'Phone / WhatsApp', email: 'Email', optional: 'optional', preferredDate: 'Preferred date (optional)', datePlaceholder: 'Select preferred date', inquiry: 'Inquiry type', message: 'Message', namePlaceholder: 'Your name', messagePlaceholder: 'Tell us the package, date, guests, or question you have for the eDrive team.', send: 'Send Inquiry', sending: 'Sending Inquiry...', received: 'Inquiry received', whatsappContinue: 'Continue on WhatsApp', receivedText: 'Thank you. Your inquiry reference is {reference}. Our team will contact you shortly.', fallbackText: 'The online inquiry service is temporarily unavailable, so your complete message has been prepared in WhatsApp to make sure it is not lost.', nameError: 'Please enter your full name.', phoneError: 'Please enter a valid phone or WhatsApp number.', emailError: 'Please enter a valid email address.', messageError: 'Please add a little more detail to your message.', submitError: 'Your inquiry could not be submitted.', inquiryTypes: ['Jet Ski Rental', 'Jet Car Rental', 'Membership', 'Group Booking', 'General Question'], whatsapp: 'WhatsApp', whatsappUs: 'WhatsApp Us', callNow: 'Call Now', bookingEmail: 'Booking Email', directions: 'Get Directions'
  },
  membership: {
    heroTitle: 'eDrive Signature Membership', heroText: 'One premium membership with priority support, special offers, VIP planning, and all key eDrive member benefits combined in one package.', heroAlt: 'eDrive Signature Membership at Dubai Islands', inquiry: 'Membership Inquiry', benefitsEyebrow: 'Member Benefits', benefitsTitle: 'More value from every eDrive experience', benefitsText: 'Designed for repeat riders, Dubai residents, couples, families, private groups, and VIP guests who want a smoother booking experience.', features: ['Member-only offers', 'Priority WhatsApp support', 'Birthday discount', 'Ride recommendations', 'Better booking support', 'Priority slots', 'Weekday offers', 'Friends/family add-on support', 'VIP planning', 'Priority sunset slots', 'Custom ride support', 'Dedicated contact flow'], comparisonTitle: 'Membership at a glance', feature: 'Feature', edrive: 'eDrive Membership', typical: 'Typical booking', included: 'Included', comparisonOthers: ['May be limited', 'Not always standard', 'Not always available', 'General support only', 'Standard booking flow', 'Subject to normal availability', 'May vary', 'May be limited', 'Often separate', 'Not guaranteed', 'Often by special request', 'Not commonly included'], ctaTitle: 'Ready to ask about membership?', ctaText: 'Message the eDrive team for current membership details and availability.', whatsapp: 'Ask on WhatsApp'
  },
  routes: {
    home: { title: 'Jet Ski Rental Dubai & Jet Car Rides | eDrive Water Sports', description: 'Book Jet Ski rentals and Jet Car rides at Dubai Islands with clear packages, flexible times, and easy online booking from eDrive Water Sports.' },
    fleet: { title: 'Jet Ski & Jet Car Fleet Dubai', description: 'Explore individual eDrive Jet Ski and Jet Car fleet units at Dubai Islands with original vehicle images, seating details, and direct package access.', heroTitle: 'Our Jet Ski & Jet Car Fleet', heroText: 'Explore the eDrive fleet with original vehicle images, registration details, seating capacity, and direct access to available ride packages.', heroAlt: 'eDrive Jet Ski and Jet Car fleet in Dubai' },
    rentals: { title: 'Water Sports Rentals', description: 'Explore current eDrive Water Sports jet ski and jet car rental packages in Dubai with clear durations, pricing, and booking support.', heroTitle: 'Water Sports Rentals', heroText: 'Explore currently available jet ski and jet car packages with clear durations, pricing, guest capacity, and direct booking support from the eDrive team.', heroAlt: 'eDrive Water Sports rentals in Dubai', packageTitle: 'Available Rental Packages', packageText: 'Choose a jet ski or jet car experience that matches your preferred duration, group size, and budget.' },
    jetSki: { title: 'Jet Ski Rental Dubai', description: 'Book a Jet Ski rental in Dubai Islands with clear durations and pricing. Choose your preferred ride time and get fast booking support from eDrive.', heroTitle: 'Jet Ski Rental Dubai', heroText: 'Ride premium Yamaha-style jet skis from Dubai Islands with clear prices, flexible durations, safety briefing, and fast booking support from the eDrive team.', heroAlt: 'eDrive jet ski rental in Dubai', packageTitle: 'Jet Ski Rental Packages', packageText: 'Choose your jet ski ride by duration, seating capacity, and price. Our team will confirm the best available slot before your experience.' },
    jetCar: { title: 'Jet Car Rental Dubai', description: 'Book a Jet Car rental at Dubai Islands with clear durations and pricing. Choose your preferred experience and request your ride online with eDrive.', heroTitle: 'Jet Car Rental Dubai', heroText: 'Enjoy a premium jet car ride in Dubai with luxury photo moments, comfortable seating, clear package options, and support from the eDrive Water Sports team.', heroAlt: 'eDrive jet car rental in Dubai', packageTitle: 'Jet Car Rental Packages', packageText: 'Choose a jet car ride by duration, seating capacity, and price. Perfect for couples, families, birthdays, photos, and premium Dubai water experiences.' },
    membership: { title: 'eDrive Signature Membership Dubai', description: 'Discover eDrive Signature Membership benefits for repeat riders, Dubai residents, couples, families, private groups, and VIP guests.' },
    booking: { title: 'Book Jet Ski & Jet Car Rides Dubai', description: 'Submit a booking request for jet ski rental, jet car rides, combo packages, family rides, and VIP water sports experiences at Dubai Islands.', heroTitle: 'Book Your Water Sports Experience', heroText: 'Choose your package, preferred date and time, then send a secure booking request to the eDrive team.', heroAlt: 'Book an eDrive Water Sports experience in Dubai' },
    myBooking: { title: 'Track My Booking', description: 'Track your eDrive Water Sports booking request using your booking code and contact details, then view its current status and submitted ride details.' },
    contact: { title: 'Contact Us Dubai', description: 'Contact eDrive Water Sports at Dubai Islands for jet ski rentals, jet car rides, memberships, package bookings, and guest support.', heroTitle: 'Contact eDrive Water Sports', heroText: 'Talk to our team about ride packages, availability, group bookings, membership, directions, or guest support.', heroAlt: 'Contact eDrive Water Sports at Dubai Islands' },
    privacy: { title: 'Privacy Policy', description: 'Read how eDrive Water Sports collects, uses, and protects customer information for website inquiries and booking requests.' },
    terms: { title: 'Terms & Conditions', description: 'Read the terms for using the eDrive Water Sports website, making booking requests, and joining water sports experiences.' },
    refund: { title: 'Refund / Replacement Policy', description: 'Read how eDrive Water Sports handles refund, replacement, rescheduling, and service change requests.' }
  },
  policies: {
    privacy: { label: 'Privacy', title: 'Privacy Policy', intro: 'This Privacy Policy explains how eDrive Water Sports collects, uses, and protects customer information when you visit our website, contact our team, or request a booking.', sections: [
      { title: 'Information we collect', text: 'When you contact us or request a booking, we may collect your name, phone number, WhatsApp number, email address, preferred date and time, service selection, number of guests, and any notes you choose to share with our booking team.' },
      { title: 'How we use your information', text: 'We use your details to respond to inquiries, confirm availability, prepare booking instructions, manage customer support, improve our service quality, and communicate important updates related to your water sports experience.' },
      { title: 'Booking and communication channels', text: `Our team may contact you through phone, WhatsApp, or email using the official eDrive Water Sports contact details, including ${companyInfo.bookingEmail}, ${companyInfo.supportEmail}, ${companyInfo.landlineDisplay}, and ${companyInfo.whatsappDisplay}.` },
      { title: 'Payment and transaction information', text: 'If online or card payment options are used, payment information may be handled by the relevant payment provider. We only keep the booking and transaction details needed for confirmation, support, and record keeping.' },
      { title: 'Data protection', text: 'We take reasonable steps to keep customer information secure and limit access to team members who need the details for booking, support, operations, or customer service purposes.' },
      { title: 'Sharing of information', text: 'We do not sell customer personal information. We may share limited information only when needed for booking operations, payment processing, service delivery, legal requirements, or customer support.' },
      { title: 'Customer rights and contact', text: `For privacy questions, corrections, or deletion requests, please contact us at ${companyInfo.supportEmail}. We may need to verify your request before making changes to booking or customer records.` }
    ] },
    terms: { label: 'Terms', title: 'Terms & Conditions', intro: 'These Terms & Conditions explain the general rules for using the eDrive Water Sports website, making booking requests, and using our water sports services.', sections: [
      { title: 'Use of our website and services', text: 'By using the eDrive Water Sports website, contacting our team, or making a booking request, you agree to use our services responsibly and provide accurate information for booking, safety, and customer support purposes.' },
      { title: 'Booking confirmation', text: 'Submitting a booking request does not automatically confirm availability. A booking is confirmed only after our team verifies the selected service, time slot, guest details, payment status when applicable, and operational conditions.' },
      { title: 'Customer responsibility', text: 'Customers must follow safety instructions, staff guidance, marina rules, and any instructions given before, during, and after the ride. Customers are responsible for arriving on time and sharing accurate contact details.' },
      { title: 'Safety and weather conditions', text: 'All rides are subject to weather, marine conditions, safety checks, government instructions, and operational availability. eDrive Water Sports may delay, reschedule, replace, or cancel an activity when needed for safety or operational reasons.' },
      { title: 'Pricing and payment', text: 'Prices, packages, and promotional offers may change depending on service type, duration, availability, and season. Any final payment amount will be confirmed by our booking team before the experience is completed.' },
      { title: 'Late arrival and no-show', text: 'Late arrival may reduce ride duration or affect the confirmed time slot. A no-show or failure to arrive within the agreed time may result in cancellation according to the applicable booking and refund policy.' },
      { title: 'Contact details', text: `For booking support, please contact ${companyInfo.bookingEmail}, call ${companyInfo.landlineDisplay}, or message us on WhatsApp at ${companyInfo.whatsappDisplay}. Our main location is ${companyInfo.locationName}.` }
    ] },
    refund: { label: 'Refunds', title: 'Refund / Replacement Policy', intro: 'This policy explains how eDrive Water Sports handles refund, replacement, rescheduling, and service change requests for bookings and customer experiences.', sections: [
      { title: 'General policy', text: 'Refunds, replacements, rescheduling, or credits depend on the booking type, payment status, timing of the request, service availability, and the reason for the change. Our team reviews each request based on the confirmed booking details.' },
      { title: 'Weather or safety changes', text: 'If a booking cannot proceed because of weather, marine conditions, safety requirements, or operational restrictions, eDrive Water Sports may offer a replacement slot, rescheduling option, alternative service, or another suitable solution.' },
      { title: 'Customer change requests', text: 'Customers should contact us as early as possible for date, time, guest count, or service changes. Requests made close to the confirmed booking time may be limited by availability and operational scheduling.' },
      { title: 'Late arrival or no-show', text: 'If a customer arrives late, the ride time may be reduced or the booking may need to be rescheduled depending on availability. No-show bookings may not be eligible for refund or replacement unless approved by management.' },
      { title: 'Replacement service', text: 'When the originally booked craft or service is unavailable, we may offer a suitable replacement craft, similar ride, alternative time slot, or service credit based on availability and customer approval.' },
      { title: 'Refund processing', text: 'Approved refunds are processed through the original or agreed payment method where possible. Processing time may depend on the payment provider, bank, or internal review requirements.' },
      { title: 'How to request support', text: `For refund, replacement, or rescheduling support, contact ${companyInfo.bookingEmail}, call ${companyInfo.landlineDisplay}, or message us on WhatsApp at ${companyInfo.whatsappDisplay}. Please include your name, booking date, service type, and reason for the request.` }
    ] }
  },
  common: { bookNow: 'Book Now', bookRide: 'Book Ride', whatsappTeam: 'WhatsApp Team', viewPackages: 'View Packages' }
};
